### ISSUE TITLE
Add some editor links

### ISSUE THREAD

**Issue by Drovosek01** [BubuAnabelas/awesome-markdown#46]
Hey. I found a few markdown editors but they are not on your list. I think it would be useful to add them.
https://github.com/notable/notable
https://boostnote.io/

**Comment by BubuAnabelas** [comment]
It would be nice to add them to the list.
You can [contribute](https://github.com/BubuAnabelas/awesome-markdown/blob/master/.github/contributing.md) by making a pull request and adding them yourself.

**Comment by Drovosek01** [comment]
> It would be nice to add them to the list.
> You can [contribute](https://github.com/BubuAnabelas/awesome-markdown/blob/master/.github/contributing.md) by making a pull request and adding them yourself.

Ok, I added some PRs. https://github.com/BubuAnabelas/awesome-markdown/pulls
