### ISSUE TITLE
Link to Awesome MD List & Projects

### ISSUE THREAD

**Issue by tajmone** [BubuAnabelas/awesome-markdown#5]
Hi @BubuAnabelas, 

I've jsut started a markdown resources project. I've added links to other similar projects, including yours:

https://github.com/tajmone/markdown-guide#awesome-markdown

Could you also add a generic links section, offering links to similar projects and Awesome Markdown lists? It makes it easier for users to find similar projects, and creates a nice web of resources.

**Comment by BubuAnabelas** [comment]
I appreciate being in your list, but as I'm trying to make a truly `awesome markdown` list it doesn't feel right to add similar stuff, as it wouldn't really contribute to the users looking for awesome markdown tools and editors.

Thank you again for adding this repo to the list! :+1:

**Comment by tajmone** [comment]
True, my repo doesn't qualify as an Awesome list. 

Thanks all the same!
