### ISSUE TITLE
add termd

### ISSUE THREAD

**Issue by dephraiim** [BubuAnabelas/awesome-markdown#72]
[termd](https://github.com/dephraiim/termd) is a cli for previewing and rendering markdown files in the terminal.

**Comment by BubuAnabelas** [comment]
It would be nice to add it to the list.
You can [contribute](https://github.com/BubuAnabelas/awesome-markdown/blob/master/.github/contributing.md) by making a pull request and adding them yourself.

**Comment by dephraiim** [comment]
Okay. Thanks
